### ISSUE TITLE
Trying to understand non termination for mapcat on colist

### ISSUE THREAD

**Issue by bsless** [HigherOrderCO/HVM#133]
Hi,
I'm playing with https://okmij.org/ftp/papers/LogicT.pdf
When I get to the implementation of logic monad interleave, the example diverges on rewrites although it should succeed.
What am I doing wrong here? Do I need to delay evaluation in some way?

```javascript
// Test driver
(Main test n) = (Test test n)

// Logic

(If 1 t e) = t
(If 0 t e) = e

// List ops
(Map f Nil        ) = Nil
(Map f (Cons x xs)) = (Cons (f x) (Map f xs))

(Concat Nil ys) = ys
(Concat (Cons x xs) ys) = (Cons x (Concat xs ys))

(Mapcat f (Cons x xs)) = (Concat (f x) (Mapcat f xs))
(Mapcat f Nil) = Nil

(Test 0 a) = (Mapcat @x(Cons x (Cons x Nil)) [1, 2, 3])

(Take n Nil) = Nil
(Take 0 _) = Nil
(Take n (Cons x y)) = (Cons x (Take (- n 1) y))

Nats = (Cons 0 (Map λx(+ x 1) Nats))

// Test take
(Test 111 n) = (Take n (Nats))

// Test mapcat and concat
(Test 112 n) = (Take n (Mapcat @a(Cons a (Cons a Nil)) Nats))
(Test 113 n) = (Concat
                (Take n (Mapcat @a(Cons a (Cons a Nil)) Nats))
                (Take n (Mapcat @a(Cons a (Cons a Nil)) Nats)))

// Monad

(Bind (Cons x xs) f) = (Mapcat f (Cons x xs))
(Bind Nil f) = Nil

(Return (Cons x xs) y) = (Cons y Nil)
(Return Nil y) = (Cons y Nil)

// Mplus

(Mplus (Cons x xs) ys) = (Concat (Cons x xs) ys)
(Mplus Nil ys) = (Concat Nil ys)

(Mzero (Cons x xs)) = Nil

// Msplit - runs computation

(Msplit (Cons x xs)) = (Cons (Just (Tuple x xs)) Nil)
(Msplit (Cons)) = (Cons Nothing Nil)
(Msplit Nil) = (Cons Nothing Nil)

// Interleave - fair disjunction

(Interleave xs ys) =
    (Bind (Msplit xs) @r(Interleave.Case r ys))

(Interleave.Case Nothing ys) = ys
(Interleave.Case (Just (Tuple x xs)) ys) =
    (Mplus (Return xs x) (Interleave ys xs))

(Test 2 a) = (Interleave [1, 2, 3, 4, 5, 6, 7] [11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

// Some tests

Odds = (Mplus
        (Cons 1 Nil)
        (Bind Odds @a(Cons (+ 2 a) Nil)))

(Test 114 n) = (Take n (Odds))

// (Test 115 n) = (Take n (Bind
//                         (Mplus (Odds) (Cons 2 Nil))
//                         @x(If (== 2 x) (Cons x Nil) Nil)))

// Works
(Test 116 n) = (Take n (Interleave (Odds) (Cons 2 Nil)))


// Works
(Test 117 n) = (Take n (Map
                        @x(If (== 2 x) (Cons x Nil) Nil)
                        (Interleave (Odds) (Cons 2 Nil))))

// Borked - mapcat?
(Test 118 n) = (Take n (Mapcat
                        @x(If (== 2 x) (Cons x Nil) Nil)
                        (Interleave (Odds) (Cons 2 Nil))))

```

Specifically, it eventually expands to `(Cons 2 (Take (- 1 1) (lots of stuff)))` at which  point I'd expect it to reduce to Take 0 and terminate

**Comment by VictorTaelin** [comment]
I don't have the time to study your code right now, but two suggestions are:

1. Use `hvm debug file.hvm` to see step-by-steep how your code is reduced.
2. Use the new `(HVM.log msg return)` feature (see the `/examples` dir) to inspect relevant parts of your reduction.

**Comment by bsless** [comment]
I'm still not sure what the problem is. I opened the ticket after running in debug mode, which is where my last remark comes in, eventually, I end up with:
```
(Cons 2 (Take (- 1 1) $(Concat a0 (Mapcat @x2 (If (= 2 a3) (Cons b3 b0) b4) (Concat (Concat (Concat (Nil) (Interleave a5 (Nil))) (Mapcat @x12 (Interleave.Case x12 b5) (Nil))) (Mapcat @x13 (Interleave.Case x13 (Cons 2 (Nil))) (Nil)))))))
dup a5 b5 = (Cons b6 b8);
dup * b1 = (Nil);
dup a9 b9 = (Nil);
dup * b8 = (Concat a9 (Mapcat @x10 (Cons b7 b9) (Concat (Nil) (Bind (Odds) @x11 (Cons (+ 2 x11) (Nil))))));
dup * b4 = (Nil);
dup a7 b7 = (+ 2 {1 x10});
dup * b6 = a7;
dup a0 b0 = b1;
dup a3 b3 = x2;
```
I'd expect (- 1 1) to get reduced to 0, then `(Take 0 ...)` to be reduced to `Nil` but it just never gets there. Instead, the chain of the recursively defined list keeps getting expanded ad infinitum.
Is it possible there's a problem with my definition of concat?

**Comment by VictorTaelin** [comment]
Isn't that because the first element of the `(Interleave (Odds) (Cons 2 Nil))` list is 1? Thus, since your Mapcat has an `if x != 2 then (Concat Nil ...)`, and since `x != 2`, then, what you're doing is, essentially, `(Concat Nil (Concat Nil (Concat Nil (Concat Nil ....))))` infinitely, so you never reach any productive output. (I may be wrong, not familiar with your algo.).

**Comment by bsless** [comment]
The algorithm:
- interleave odds and [2]
- mapcat `@x(If (== 2 x) (Cons x Nil) Nil)`
- take the first element
my expectation, which may be wrong, is that the runtime is lazy, thus I can take the first element, while even trying to take the second will diverge.
As you can see It ends up Consing the `2` out of that interleaved list, but (Take (-1 1) ...) isn't ever reduced to (Take 0 ...), the other argument to Take keeps getting expanded

**Comment by VictorTaelin** [comment]
Ah - HVM has a weird (that, to be fair, was accidental and I should change) property that it evaluates argument from right to left. So, it attempts to first evaluate the second argument of Take, which loops (because you're trying to get the head of an infinite `(Concat Nil (Concat Nil ...))`), so it never has the chance of evaluating the first argument. You're right that your program would normalize if it did it in the opposite order (but then it would loop again if you inverted the order of `Take`).

**Comment by bsless** [comment]
Huh, that's peculiar.
Is there a way to sort of round-robin arguments reduction? There's no reason to prioritize one over the other in terms of processing time. And it violates laziness

**Comment by bsless** [comment]
To add a bit on the subject, it has a curious overlap with the paper I've been playing with in this thread:
Fair evaluation (e.g. `or`) should interleave execution, it's BFS and not DFS. Composition (application?) is analogous to `and`, and can also be interleaved in a fairer manner.
In Clojure it would look like:

```
(extend-protocol ILogicM
  nil
  (-interleave [_ sg2] sg2)
  (>>- [_ g] nil)

  clojure.lang.ISeq
  (-interleave [sg1 sg2]
    (lazy-seq
     (if-let [[sg11 & sg12] (seq sg1)] ;; like matching on (Cons x xs) or Nil
       (cons sg11 (-interleave sg2 sg12))
       sg2)))
  (>>- [sg g]  ;; this is fair bind
    (lazy-seq
     (if-let [[sg1 & sg2] (seq sg)]
       (-interleave (g sg1) (>>- sg2 g))
       ()))))
```

**Comment by VictorTaelin** [comment]
Yep, that sounds right. HVM wasn't made with that in mind, but interleaving computations would be really cool. Note that the parallel version does that, to an extent, since it sparks a thread to reduce each argument independently. But surely that is one (of the many) areas that can be improved.

**Comment by bsless** [comment]
Since HVM is supposed to be fully lazy and in this exercises it eagerly evaluates an infinite computation, should it be considered a bug?
Not trying to create extra work for you, even if it is a bug you got other priorities as well, but I'm not sure how to proceed with from here :upside_down_face:

**Comment by VictorTaelin** [comment]
I don't think this is bug, GHC will exhibit the same behavior, no? Interleaved computation would impact performance, so that isn't desirable. I don't think the usual definition of laziness covers interleaved execution of parallel matches, and I've never seen a language behave that way. In fact that concept isn't even *possible* on the λ-calculus, since there aren't parallel matches to begin with. HVM's lambda calculus is as lazy as technically possible. That is just my analysis of the subject, but I may be wrong, let me know if you think that is the case.

**Comment by bsless** [comment]
I don't think you are wrong, I guess the fundamental question is:
Does the runtime need to reduce all the arguments to reach a valid redex?
If I have `(Foo x y) = x` I never need to reduce `y` to reduce `(Foo x y)`
In my use case I have `(Take 0 xs) = Nil`, but reduction never ends up with that 0.

Why would interleaving computations be too expansive?

Anyway, there are some ML papers on selecting the optimal order of matching:
[Compiling Pattern Matching to good Decision Trees](https://www.cs.tufts.edu/~nr/cs257/archive/luc-maranget/jun08.pdf)
This could probably be a reasonable compromise and an optimization. Also see example implementation https://github.com/clojure/core.match/wiki/Understanding-the-algorithm

Do you have advice or thoughts on how I should proceed now with my case?

**Comment by VictorTaelin** [comment]
> Why would interleaving computations be too expansive?

I'm not sure, but I can't think of a way to do it right now. That's a great idea overall, if possible to implement.

**Comment by bsless** [comment]
I don't know why, but it reminds me of Dan Friedman's work on Frons, which are a sort of data structure X computation engine which managed to fairly allocate computational resources to different branches of computation.
It's like two orthogonal problems - the abstract algorithm of efficiently reducing lambda terms, and an abstract computer, which efficiently, correctly and fairly executes those reductions.

**Comment by ydewit** [comment]
I am experiencing what I think is a similar behavior although I am not sure if I am doing something wrong here:

Consider the following mwe:
```
(If 1 t f) = t
(If 0 t f) = f

(Force (Delay c)) = c
(Force x        ) = x

(Loop n) = (Delay (If (== n 0) Done (Loop (- n 1))))

(Main) = (Loop 4)
```
I was (naively) expecting this to finish early with: `Delay (If (= a0 0) (Done) (Loop (- b0 1)))`. But HVM is reducing the inner redexes until I get: `(Delay (Delay (Delay (Delay (Delay (Done))))))`, which was not what I had in mind with the notion of **Delay** and **Force**.

I then tried to wrap the delay value in a lambda:
```
(If 1 t f) = t
(If 0 t f) = f

(Force (Delay f c)) = (f c)
(Force x               ) = x

(Loop n) = (Delay λn(If (== n 0) Done (Loop (- n 1))) n)

(Main) = (Loop 4)
```
But the same happens: Loop is reduced inside the delay.

--- 

Now why this works when using lists as described in the copatterns example (i.e. `Nats = (Cons 0 (Map λx(+ x 1) Nats))`). Is there something special about lists that make it work or I am missing something obvious?

**Comment by ydewit** [comment]
@bsless Setting aside the lazy vs strict vs unbounded recursion issue, couldn't you achieve interleaving by switching the "rest of the stream" in MPlus:
```
...
(MPlus (List.cons x xs) list) = (List.cons x (MPlus list xs)) // invert list to interleave
```
Or are you trying to keep MPlus without interleaving the streams and then layer interleaving on top of it?

**Comment by bsless** [comment]
@ydewit I wanted to go for a straightforward implementation of the paper, where mplus is monadic concat and interleave is implemented with mplus and bind:
```javascript
// Interleave - fair disjunction

(Interleave xs ys) =
    (Bind (Msplit xs) @r(Interleave.Case r ys))

(Interleave.Case Nothing ys) = ys
(Interleave.Case (Just (Tuple x xs)) ys) =
    (Mplus (Return xs x) (Interleave ys xs))
```

**Comment by bsless** [comment]
Just checking in, ran with latest version of HVM and still run into this issue
Latest version of code:
```javascript
(Logs (List.cons x xs)) = (HVM.log x (Logs xs))
(Logs []) = (HVM.log (DONE) [])

(String.concat String.nil         ys) = ys
(String.concat (String.cons x xs) ys) = (String.cons x (String.concat xs ys))

(Eq (List.cons x xs) (List.cons y ys)) = (If (Eq x y) (Eq xs ys) 0)
(Eq [] []) = 1
(Eq (List.cons x xs) a) = 0
(Eq a (List.cons x xs)) = 0

(Eq a b) = (== a b)

(If 1 t e) = t
(If 0 t e) = e

(Testing that expected actual) =
    (String.concat (If (Eq expected actual) "PASS: " "FAIL: ") that)

// List ops
(Map f []        ) = []
(Map f (List.cons x xs)) = (List.cons (f x) (Map f xs))

TestMapEmpty = (Testing "Map on empty list is empty list" [] (Map @x(+ x 1) []))
TestMap = (Testing "Map on list" [1,2,3] (Map @x(+ x 1) [0,1,2]))

(First (List.cons x xs)) = x
(Rest (List.cons x xs)) = xs

// (Concat xs []) = xs
(Concat [] ys) = ys
(Concat (List.cons x xs) ys) = (List.cons x (Concat xs ys))
// (Concat xs (List.cons y ys)) = (List.cons x (Concat xs ys))

TestConcatLeftEmpty = (Testing "Concat with left empty list" [1,2,3] (Concat [] [1, 2, 3]))
TestConcatRightEmpty = (Testing "Concat with right empty list" [1,2,3] (Concat [1, 2, 3] []))
TestConcatBothEmpty = (Testing "Concat with both empty list" [] (Concat [] []))
TestConcatLists = (Testing "Concat with both empty list" [1,2,3,4] (Concat [1,2] [3,4]))

(Mapcat f (List.cons x xs)) = (Concat (f x) (Mapcat f xs))
(Mapcat f []) = []

TestMapCat = (Testing "Mapcat flattens one level" [1,2,2,3] (Mapcat @x([x,(+ 1 x)]) [1,2]))

(Take n []) = []
(Take 0 _) = []
(Take n (List.cons x y)) = (List.cons x (Take (- n 1) y))

TestTakeEmpty = (Testing "Take from empty list" [] (Take 3 []))
TestTakeZero = (Testing "Take zero from list" [] (Take 0 [1,2,3]))
TestTake = (Testing "Take zero from list" [1,2] (Take 2 [1,2,3]))


Nats = (List.cons 0 (Map λx(+ x 1) Nats))

TestRecursiveDefNats = (Testing "Recursive definition of natural numbers" [0,1,2,3] (Take 4 Nats))

// Monad
(Bind (List.cons x xs) f) = (Mapcat f (List.cons x xs))
(Bind [] f) = []
(Return (List.cons x xs) y) = [y]
(Return [] y) = [y]


// Mplus

(Mplus (List.cons x xs) ys) = (Concat (List.cons x xs) ys)
(Mplus [] ys) = (Concat [] ys)

(Mzero (List.cons x xs)) = []
(Mzero []) = []

// Msplit - runs computation

(Msplit (List.cons x xs)) = (List.cons (Just (Tuple x xs)) [])
(Msplit []) = (List.cons Nothing [])


// Interleave - fair disjunction

(Interleave xs ys) =
    (Bind (Msplit xs) @r(Interleave.Case r ys))

(Interleave.Case Nothing ys) = ys
(Interleave.Case (Just (Tuple x xs)) ys) =
    (Mplus (Return xs x) (Interleave ys xs))

TestInterleave = (Testing "Interleave two seqs" [1,2,3,4,5] (Interleave [1,3,5] [2,4]))

Odds = (Mplus [1] (Bind Odds @a(List.cons (+ 2 a) [])))

TestOdds = (Testing "Recursive monadic definition for sequence" [1,3,5] (Take 3 Odds))

OddsP = (Interleave (Odds) [2,4,6])

TestInterleavedOdds = (Testing "Interleave recursive monadic with finite sequence" [1,2,3,4] (Take 4 OddsP))
TestInterleavedOdds. =
    (Testing "Interleave finite sequence with recursive monadic" [2,1,4,3] (Take 4 (Interleave [2,4,6] (Odds))))

TestInterleaveOddsNats =
    (Testing "Interleave Odds and Nats" [1, 0, 3, 1] (Take 4 (Interleave Odds Nats)))

TestInterleaveNatsOdds =
    (Testing "Interleave Nats and Odds" [0, 1, 1, 3] (Take 4 (Interleave Nats Odds)))


TestMapcatInterleavePrim0 =
    (Testing "Take mapcat conditional interleave"
     []
     (Take 0 (Mapcat @x(x) (Map @x(If (== 2 x) [x] []) (Interleave Odds [2])))))

TestMapcatInterleavePrim1 =
    (Testing "Take mapcat conditional interleave"
     [1]
     (Take 1 (Mapcat @x(x) (Map @x(If (== 2 x) [x] []) (Interleave Odds [2])))))

TestMapcatInterleave =
    (Testing "Take mapcat conditional interleave"
    [2]
     (Take 1 (Mapcat @x(If (== 2 x) [x] []) (Interleave Odds [2]))))

Main =
    (Logs
     [(TestMapEmpty),
      (TestMap),
      (TestConcatLeftEmpty),
      (TestConcatRightEmpty),
      (TestConcatBothEmpty),
      (TestConcatLists),
      (TestMapCat),
      (TestTakeEmpty),
      (TestTakeZero),
      (TestTake),
      (TestRecursiveDefNats),
      (TestInterleavedOdds),
      (TestInterleavedOdds.),
      (TestInterleaveOddsNats),
      (TestInterleaveNatsOdds),
      (TestMapcatInterleavePrim0)])
```

Any advice or guidance welcome

**Comment by kings177** [comment]
sorry for the delay in answering. as HVM is now HVM2, a lot of things changed, so i am closing this issue, as it no longer corresponds to anything related to the current HVM iteration.

**Comment by bsless** [comment]
Understandable. Is there a guide on migrating HVM code to HVM2?

**Comment by kings177** [comment]
not currently, since HVM2 is a low-level syntax language, we recommend people using [Bend](https://github.com/HigherOrderCO/Bend) instead, which is our high-level language to interact with HVM. We have a [GUIDE](https://github.com/HigherOrderCO/Bend/blob/main/GUIDE.md) for Bend.
