### ISSUE TITLE
Compiled HVM programs need a better CLI interface

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/HVM#188]
Running a program compiled with `hvm compile somefile.hvm` and then `cargo build --release`, I am greeted with this message

```
$ ./target/release/somefile 

somefile 1.0.17-beta
A massively parallel functional runtime.

USAGE:
    somefile <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    compile    Compile a file to Rust
    help       Print this message or the help of the given subcommand(s)
    run        Load a file and run an expression
```

That means that this program is not carrying only the interpreted and precompiled functions, but also the whole compiler.

That is unintuitive, what I expected was to just be able to call my program directly (which would correspond to calling it with `somefile run "(Main arg)"`).

We should probably create a separate CLI for the compiled programs to make this simpler to use

**Comment by VictorTaelin** [comment]
Makes sense to me. Will add.
