### ISSUE TITLE
Make `Runtime` fields public?

### ISSUE THREAD

**Issue by zicklag** [HigherOrderCO/HVM#194]
I'm not sure this is the best design or not, but I wanted to open the discussion about making the fields of `Runtime` public.

I love the convenience of the methods on `Runtime`, but I was also wanting to play around with modifying the rulebook manually at runtime, and if I use `Runtime` to create the rulebook, there's no way to access the rulebook or the heap or anything else inside of it.

**Comment by VictorTaelin** [comment]
I'm a huge non-enjoyer of private fields for that reason. I'm not coding this week, but will make them public in a future release.

**Comment by zicklag** [comment]
Closed in #207.
