### ISSUE TITLE
List of builtin modules and functions?

### ISSUE THREAD

**Issue by frehberg** [HigherOrderCO/HVM#211]
Is there a list of builtin modules and functions anywhere?

How to define a module and how to define a dependency in my program? How to organize the custom modules and is there any search path being used?

**Comment by developedby** [comment]
The builtin, precompiled functions, that HVM has by default are defined in `/src/runtime/base/precomp.rs`.

When you compile an HVM program it basically appends some more items there. If you want to add your own custom functions there, I think right now you must put all of them in an HVM file, compile it and then copy the autogenerated `precomp.rs` back to the original HVM repo.
