### ISSUE TITLE
New Error ->error[E0599]: no method named `as_mut_ptr` found for struct `AtomicU64` in the current scope

### ISSUE THREAD

**Issue by verbus** [HigherOrderCO/HVM#212]
Some of the details are:

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.69.0-nightly (31f858d9a 2023-02-28)

info: checking for self-updates
    Updating git repository `https://github.com/Kindelia/HVM.git`
  Installing hvm v1.0.2 (https://github.com/Kindelia/HVM.git#573e9e2d)
    Updating crates.io index
.
.

Compiling instant v0.1.12
   Compiling hvm v1.0.2 (/home/verbus/.cargo/git/checkouts/hvm-a2339bb8b9261392/573e9e2)
error[E0599]: no method named `as_mut_ptr` found for struct `AtomicU64` in the current scope
   --> src/runtime/base/memory.rs:450:54
    |
450 |         let val = heap.node.get_unchecked(*lvar.next.as_mut_ptr() as usize).load(Ordering::Relaxed);
    |                                                      ^^^^^^^^^^ help: there is a method with a similar name: `as_ptr`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `hvm` due to 14 previous errors
error: failed to compile `hvm v1.0.2 (https://github.com/Kindelia/HVM.git#573e9e2d)`, intermediate artifacts can be found at `/tmp/cargo-installsTN1UZ`

This was the script the above was run from:

#!/usr/bin/env bash
rustup install nightly
cargo +nightly install --force --git https://github.com/Kindelia/HVM.git

**Comment by developedby** [comment]
[This PR](https://github.com/rust-lang/rust/pull/107736) in Rust nightly changed the name of this function to just `as_ptr`. I'll send a fix in a moment

**Comment by developedby** [comment]
@verbus can you check that it works for you now?
