### ISSUE TITLE
Compiling hvm v1.0.3 - error[E0635]: unknown feature `atomic_mut_ptr`

### ISSUE THREAD

**Issue by verbus** [HigherOrderCO/HVM#221]
Compiling hvm v1.0.3 (/home/verbus/.cargo/git/checkouts/hvm-a2339bb8b9261392/ce01625)
error[E0635]: unknown feature `atomic_mut_ptr`
--> src/lib.rs:2:12
  |
2 | #![feature(atomic_mut_ptr)]
| ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `hvm` (lib) due to previous error
error: failed to compile `hvm v1.0.3 ([https://github.com/Kindelia/HVM.git#ce01625d)`](https://github.com/Kindelia/HVM.git#ce01625d)), intermediate artifacts can be found at `/tmp/cargo-installL9RCJn`

---
$ uname -a
Linux verbus-Aspire-Z3-605 6.1.0-16-generic #16-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 24 14:37:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

nightly-x86_64-unknown-linux-gnu updated - rustc 1.70.0-nightly (ab654863c 2023-03-15) (from rustc 1.70.0-nightly (171693274 2023-03-14))

**Comment by zicklag** [comment]
This happned just a day or two ago when they stabilized the previously unstable feature. I have an open PR to fix the build: #220.
