### ISSUE TITLE
fixed-point combinator hangs when using more than one thread

### ISSUE THREAD

**Issue by nivkner** [HigherOrderCO/HVM#232]
using the following code:

```idris
Y = λf ((λx (f (x x))) (λx (f (x x))))

Factorial = λf (λn ( U60.if (== n 0) 1 (* n (f (- n 1)))))

(Main n) = (((Y) Factorial) n)
```

the following command hangs:
`hvm run -f fixed_point.hvm "(Main 5)"`

whereas the following command terminates with `120` as expected:
`hvm run -f fixed_point.hvm "(Main 5)" --debug`

tested on commit `d3367849ec92a043ebf04fe537e9b74c516347b6`, with rust `nightly-2023-03-01`

Edit: might be a deadlock of some sort, which debugging prevents by serializing execution.
since similar results are gotten when specifying `-t 1` instead

**Comment by Boscop** [comment]
I noticed the same behavior on my machine, also with the Y combinator:
```js
Y = λf ((λx (f (x x))) (λx (f (x x))))
(Main n) = ((Y) (λf λi (U60.if (== i n) Done (f (+ i 1)))) 0)
```
Without `--debug` flag, it works when calling `(Main 2)`, but with `(Main 3)` it uses all CPU cores and doesn't return..
