### ISSUE TITLE
Unnecessary unsafe in `new_atomic_u64_array`

### ISSUE THREAD

**Issue by Boscop** [HigherOrderCO/HVM#245]
https://github.com/HigherOrderCO/HVM/blob/9a6f6ff84cc6d5eb6aa802676ca19c34884e2db8/src/runtime/base/memory.rs#L394-L398

This could just be `vec![0; n].into_iter().map(|x| AtomicU64::new(x)).collect::<Vec<_>>().into_boxed_slice()`, it compiles to a call to `alloc_zeroed` without any `memset` (it reuses the allocated Vec):
https://godbolt.org/z/Ebrn4aaW7

(Btw, when using `Box::from_raw`, it's more recommended to pair it with `Box::into_raw`:
https://users.rust-lang.org/t/can-box-leak-be-complemented-with-box-from-raw/64478/2
So it would be written as `Box::into_raw(...) as *mut [AtomicU64]` and a static assertion that they have the same alignment requirement.)

**Comment by howsiyu** [comment]
Or just `vec![0u64; size].into_iter().map(AtomicU64::new).collect()`
