### ISSUE TITLE
Incorrect statement in HOW.md

### ISSUE THREAD

**Issue by kazimuth** [HigherOrderCO/HVM#248]
Hi, lovely project! This is very neat.

I have one complaint about the HOW document. In the section "Everyone's solution: ban the clones", there is the statement: "Sadly, such a language wouldn't be practical. Imagine never being able to copy anything!"

This is simply incorrect. There is a long line of research on languages that never copy or delete data (although they do permute data.) These languages have fascinating properties -- in particular, they can always be run in reverse. For this reason the research area is called [reversible computing](https://en.m.wikipedia.org/wiki/Reversible_computing). It is related to quantum computing, and adiabatic computing, which is computation that generates arbitrarily small amounts of heat. Mathematically, it corresponds to a shift from categories to groupoids.

Such languages can in fact simulate any turing machine with a polynomial time slowdown and the same asymptotic space bounds and may offer dramatic benefits for hardware implementation. So it is best not to dismiss them out of hand :)

**Comment by VictorTaelin** [comment]
I don't disagree with you. Writing is hard because you need to appeal and predict the entire spectrum of human opinions and reactions.
