### ISSUE TITLE
Rule flattening fails in some cases

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/HVM#254]
While trrying to write a function that matched on longer string in Kind, I've run into the issue that HVM is not able to properly handle them.

It seems that in some cases where there are nested constructors using a mix of numbers and other constructors, the rule flatenning algorithm fails to produce a valid output.  

I've found this minimal example:
```(Foo 0 (A B)) = B```
Which crashes with `thread 'main' panicked at 'inconsistent arity on: '(Foo.0 x0.0)'`

The error only arises when we have a number at one level of nesting and then some other constructor with deeper nesting in the same rule.

**Comment by developedby** [comment]
Looks like `language/rulebook.rs:flaten::split_group()`  produces
```
(Foo (A .1)) = (Foo.0 .1)
(Foo.0 0 (B)) = (B)
```
instead of the expected
```
(Foo 0 (A .1)) = (Foo.0 .1)
(Foo.0 (B)) = (B)
```

**Comment by kings177** [comment]
closing the issue as HVM is now HVM2 and this no longer pertains.
