### ISSUE TITLE
https://kindelia.org appears to be offline -- is this on purpose?

### ISSUE THREAD

**Issue by johnnyutahh** [HigherOrderCO/HVM#257]
https://kindelia.org (referenced in the `About` section of this github repo "top page")) appears to be offline, at least for me within the last 16 hours or so.

Is this on purpose?

**Comment by VictorTaelin** [comment]
@kings177

**Comment by kings177** [comment]
> https://kindelia.org (referenced in the `About` section of this github repo "top page")) appears to be offline, at least for me within the last 16 hours or so.
> 
> Is this on purpose?

yes, the website has been changed to [higherorderco.com](https://higherorderco.com), i just forgot to redirect it, thank you for letting us know.
