### ISSUE TITLE
Cargo warning: output filename collision

### ISSUE THREAD

**Issue by JSorngard** [HigherOrderCO/HVM#260]
When I run `cargo +nightly install hvm` I get the following warning:

    warning: output filename collision.
    The bin target `hvm` in package `hvm v1.0.10` has the same output filename as the lib target `hvm` in package `hvm v1.0.10`.
    Colliding filename is: C:\Users\<USERNAME>\AppData\Local\Temp\cargo-install<HASH>\release\hvm.pdb
    The targets should have unique names.
    Consider changing their names to be unique or compiling them separately.
    This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.

**Comment by kings177** [comment]
sorry for the late response, but that was due to our developing of HVM2 (which is now currently in this repo), and since it's live in this repo, `cargo +nightly install hvm` should work properly now, thanks for taking time to open the issue, and again, sorry for the delay in response :)
