### ISSUE TITLE
TOIOFPL link aims at a book about category theory

### ISSUE THREAD

**Issue by kozross** [HigherOrderCO/HVM#264]
I was quite confused by this at first: the authors are the same, but the book's topic definitely doesn't relate to implementing functional languages, at least not in a direct sense.

**Comment by Janiczek** [comment]
From introduction of that book:
> This book is about optimal sharing in functional programming languages.

It's not the same kind of book as eg. Simon Peyton Jones's "The Implementation of Functional Programming Languages", and instead deals with interaction nets and sharing and a very specific meaning of the word "optimal". This is not a mistake IMHO. How is your raised issue actionable? The link is correct already.

**Comment by kozross** [comment]
If I follow [the link](https://www.researchgate.net/publication/235778993_The_optimal_implementation_of_functional_programming_languages), and then click 'Download full-text PDF' (or scroll down, same thing), I see this:

![Screenshot from 2024-02-16 06-33-02](https://github.com/HigherOrderCO/HVM/assets/8463904/a75912eb-a697-4652-89ec-c953d7288f26)

I think we can both agree that's not the right book, which I assume is [actually this one](https://www.amazon.com/Implementation-Functional-Programming-Languages-Theoretical/dp/0521621127).

**Comment by VictorTaelin** [comment]
oh no, should be the optimal implementation of functional programming languages

@kings177 can you fix? link to the proper citation

**Comment by kings177** [comment]
yes, on it, @kozross thank you for pointing it out.

**Comment by Janiczek** [comment]
@kozross Apologies, serves me right for not checking the actual link and interpreting your message as "TOIOFPL is not about functional languages" 😅
