### ISSUE TITLE
Inaccurate categorisation of bubble sort in README.md

### ISSUE THREAD

**Issue by Vi-Kitten** [HigherOrderCO/HVM#265]
This is minor, but bubble sort actually **can** be parallelised.

By analysing the [sorting network](https://en.wikipedia.org/wiki/Sorting_network) of bubble sort and insert sort we can deduce:
- They are the same sorting algorithm *from a sorting network perspective*.
- They can be parallelised by computing the swaps of every other pair at the same time, as described in [this section](https://en.wikipedia.org/wiki/Sorting_network#Insertion_and_Bubble_networks) of the linked article.

Here is a diagram from that article showing how this is done:
![pyramid-sorting-network svg](https://github.com/HigherOrderCO/HVM/assets/119464866/d61ee188-a0fe-4286-918e-fd44abd55cbd)
(you may want to open the image in another tab to see it better)

In general a lot of sorting algorithms can be optimised this way by looking at their sorting networks.

**Comment by VictorTaelin** [comment]
You're correct! In the README, I just meant that **that** algorithm, as written, couldn't (because it is implemented as a sequential loop). But the article should improved with that in mind.

**Comment by kings177** [comment]
@Vi-Kitten thank you for pointing it out :)
