### ISSUE TITLE
Function names longer than 32 bytes don't work

### ISSUE THREAD

**Issue by CatsAreFluffy** [HigherOrderCO/HVM#303]
https://github.com/HigherOrderCO/HVM/blob/542ca9884428924c559beeeda2786abaec81defa/src/hvm.rs#L930 underflows for function names longer than 32 bytes, causing an immediate crash if HVM is compiled in debug mode, and inscrutable errors later if it's compiled in release mode.

**Comment by kings177** [comment]
Closing since fixed
