### ISSUE TITLE
Error reading result from hvm. Output 

### ISSUE THREAD

**Issue by SAKSoomro** [HigherOrderCO/HVM#310]
**Bug description**
bend works ok on single core cpu and with all cores but gives error with gpu

**Command**
$ bend run-cu app.bend 

**Error**
Errors: Error reading result from hvm. Output : Failed to launch kernels (error code the provided PTX was compiled with an unsupported toolchain.)! exit status: 1

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04.3 LTS on WSL Windows 11
 - CPU: 12th Gen Intel i9-12900
 - GPU: RTX A2000 12GB
 - Cuda Version  cuda 12.4

**Comment by kings177** [comment]
the current iteration of the cuda version of hvm was made with the 4090's shared mem number hardcoded, which is 96KB, and if you run with your A2000 (or any "older" GPU), which have 48KB (or less) of shared mem, this error will occur. we plan on soon release a refactored version with a dynamic number for the shared mem
