### ISSUE TITLE
tools for visualizing and plotting interaction net graphs?

### ISSUE THREAD

**Issue by anandijain** [HigherOrderCO/HVM#316]
on the hoc website video, (at least currently), there is an animation that takes 3x3, turns it into a graph, uses the IC rules to find fixpoint, then returns back the expr.

is there any plans or existing tooling to generate those diagrams? I think it would help me understand hvm and bend if I could see what graph the compiler outputs.

thank you!

**Comment by developedby** [comment]
I'm pretty sure those were done semi-manually.
I'm aware of these two:
https://github.com/eduhenke/inet-vis
https://github.com/FranchuFranchu/inet-grapher
And some people have in the past have tried using graphviz, but I lost track of where it is.

They are not very good though, and we'd like to have a better version at some point

**Comment by kings177** [comment]
the graph itself was hand-drawn. yes. they one's that we have for automatically creating the graphs aren't that good looking tho, that's the benefit of hand-drawing.

**Comment by enricozb** [comment]
Closing as this isn't something that would live in the HVM repo.

**Comment by anandijain** [comment]
thanks makes sense. my understanding is `bend gen-hvm` outputs HVM's IR basically. but is that the graph? 

my guess would be this still somehow is lowered once more to the actual graph, but i haven't looked. 

is there a way to go from a `.hvm` file to something more like graphviz with node and edge lists?

thanks!
