### ISSUE TITLE
Numeric Type Conversion

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/HVM#322]
**Is your feature request related to a problem? Please describe.**
Currently to convert from integer to float we have to do an expensive bit-by-bit transformation, over 30 interactions.
It'd be nice if the HVM either exposed the native casting operation or provided operations that allowed for this to be done cheaply.

**Describe the solution you'd like**
We could define the interaction `SYM(TYP1) ~ OP(NUM(TYP2) x)` to produce `NUM(TYP1) ~ x`, doing the appropriate casting.
Currently it produces `0 ~ x`.
For float to integer it should truncate the value.

**Describe alternatives you've considered**
An alternative that doesn't require changing the OPER interaction semantics, would be to add a CLZ (count leading zeros) operation and a rounding/truncating operation.

CLZ allows converting uint to float cheaply by directly providing a way to get the exponent.
Int to float requires flipping the bits first, but it's basically the same.
However, this requires duplicating the number to convert to a float (one copy for exponent, one for mantissa), so not ideal.

A rounding operation converts from float to int and then we can easily convert to uint.

**Additional context**
There are many algorithms that work by incrementing a counter and then using that counter in a float operations. This could be done by incrementing a float, but it stops working at some point.
It also makes comparing the integer values a problem, since they're now floats and have intrinsic errors.

**Comment by VictorTaelin** [comment]
We'll be adding a CLZ/CRZ probably regardless since it is important for many algorithms, but I also think the cast interaction should be included, specially since it doesn't cost an extra op.
