### ISSUE TITLE
PARSE_ERROR - expected: name trying to run a `.hvm` outputted from `bend gen-hvm` 

### ISSUE THREAD

**Issue by anandijain** [HigherOrderCO/HVM#329]
i just cloned Bend and HVM (both on main). i have `c` alias to cargo. i am using wsl2 windows 11

I first did `c r --release -- gen-hvm examples/parallel_hello_world.bend >> hello.hvm` in the bend repo which I believe gives me something that hvm should be able to run. I verified that `c r --release -- run examples/parallel_hello_world.bend` runs fine alone.

however, my understanding is that I can take the result of `gen-hvm` and then in the HVM repo run the compiler like `c r --release -- run-c hello.hvm` or `run` or `run-cu`. I don't have a compatible gpu, but here are the outputs of trying to run the `hello.hvm` with hvm and c.

```
anand@jain ~/d/b/HVM (main) [101]> c r --release -- run hello.hvm
warning: hvm@2.0.14: WARNING: CUDA compiler not found. HVM will not be able to run on GPU.
    Finished `release` profile [optimized] target(s) in 0.01s
     Running `target/release/hvm run hello.hvm`
thread 'main' panicked at src/main.rs:70:62:
PARSE_ERROR
- expected: name
- detected:
   8 | @gen__bend0 = ({$(:[<] $(a ?((@gen__bend0__C0 @gen__bend0__C1) (b (c d))))) b} ({a c} d))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
anand@jain ~/d/b/HVM (main) [101]> c r --release -- run-c hello.hvm
warning: hvm@2.0.14: WARNING: CUDA compiler not found. HVM will not be able to run on GPU.
    Finished `release` profile [optimized] target(s) in 0.01s
     Running `target/release/hvm run-c hello.hvm`
thread 'main' panicked at src/main.rs:76:62:
PARSE_ERROR
- expected: name
- detected:
   8 | @gen__bend0 = ({$(:[<] $(a ?((@gen__bend0__C0 @gen__bend0__C1) (b (c d))))) b} ({a c} d))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I don't have enough experience to really debug further

**Comment by developedby** [comment]
I forgot to publish the new Bend version, sorry

**Comment by anandijain** [comment]
but if im using main isn't `cargo run` going to use the correct, up-to-date bend, or do i need to pull again

**Comment by developedby** [comment]
Try installing the latest Bend and latest HVM

**Comment by anandijain** [comment]
```
anand@jain ~/d/b/Bend (main) [2]> bend gen-hvm examples/parallel_hello_world.bend >> hello.hvm
anand@jain ~/d/b/Bend (main)> hvm run hello.hvm 
Result: 1966082
- ITRS: 4849622
- TIME: 0.21s
- MIPS: 23.14

```

works great thanks, i would prefer to be able to use from source but not big deal

**Comment by developedby** [comment]
Latest published versions of both should be the latest commit on github (in fact that should always be the case unless someone forgets to publish), no problem with using version from github
