### ISSUE TITLE
unsupported GNU version! gcc versions later than 12 are not supported!

### ISSUE THREAD

**Issue by vak** [HigherOrderCO/HVM#343]
### Reproducing the behavior

cargo +nightly install hvm
    Updating crates.io index
  Downloaded hvm v2.0.16
  Downloaded 1 crate (620.9 KB) in 0.11s
  Installing hvm v2.0.16
    Updating crates.io index
     Locking 29 packages to latest compatible versions
  Downloaded anstream v0.6.14
  Downloaded cc v1.0.98
  Downloaded is_terminal_polyfill v1.70.0
  Downloaded anstyle-query v1.0.3
  Downloaded TSPL v0.0.12
  Downloaded utf8parse v0.2.1
  Downloaded anstyle-parse v0.2.4
  Downloaded num_cpus v1.16.0
  Downloaded strsim v0.11.1
  Downloaded highlight_error v0.1.1
  Downloaded colorchoice v1.0.1
  Downloaded anstyle v1.0.7
  Downloaded clap v4.5.4
  Downloaded clap_lex v0.7.0
  Downloaded clap_builder v4.5.2
  Downloaded libc v0.2.155
  Downloaded 16 crates (1.2 MB) in 0.15s
   Compiling libc v0.2.155
   Compiling utf8parse v0.2.1
   Compiling is_terminal_polyfill v1.70.0
   Compiling anstyle v1.0.7
   Compiling anstyle-query v1.0.3
   Compiling colorchoice v1.0.1
   Compiling clap_lex v0.7.0
   Compiling strsim v0.11.1
   Compiling cc v1.0.98
   Compiling highlight_error v0.1.1
   Compiling TSPL v0.0.12
   Compiling anstyle-parse v0.2.4
   Compiling anstream v0.6.14
   Compiling clap_builder v4.5.2
   Compiling num_cpus v1.16.0
   Compiling hvm v2.0.16
The following warnings were emitted during compilation:

warning: hvm@2.0.16: In file included from /usr/include/cuda_runtime.h:83,
warning: hvm@2.0.16:                  from <command-line>:
warning: hvm@2.0.16: /usr/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
warning: hvm@2.0.16:   132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
warning: hvm@2.0.16:       |  ^~~~~

error: failed to run custom build command for `hvm v2.0.16`

### System Settings

Example:
 - OS: Ubuntu 24.04
 - GPU: RTX 4090
 - Cuda Version: 
```
 % nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0[e.g. release 12.4, V12.4.131]

% apt list --installed |grep -i cuda
libcudart12/noble,now 12.0.146~12.0.1-4build4 amd64 [installed,automatic]
nvidia-cuda-dev/noble,now 12.0.146~12.0.1-4build4 amd64 [installed,automatic]
nvidia-cuda-gdb/noble,now 12.0.140~12.0.1-4build4 amd64 [installed,automatic]
nvidia-cuda-toolkit-doc/noble,now 12.0.1-4build4 all [installed,automatic]
nvidia-cuda-toolkit/noble,now 12.0.140~12.0.1-4build4 amd64 [installed]

% apt list --installed |grep -i nvidia
libnvidia-cfg1-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
libnvidia-common-550/noble,now 550.67-0ubuntu3 all [installed,automatic]
libnvidia-compute-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
libnvidia-decode-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
libnvidia-encode-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
libnvidia-extra-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
libnvidia-fbc1-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
libnvidia-gl-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
libnvidia-ml-dev/noble,now 12.0.140~12.0.1-4build4 amd64 [installed,automatic]
linux-objects-nvidia-535-6.8.0-31-generic/noble,now 6.8.0-31.31 amd64 [installed,automatic]
linux-signatures-nvidia-6.8.0-31-generic/noble,now 6.8.0-31.31 amd64 [installed,automatic]
nvidia-compute-utils-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
nvidia-cuda-dev/noble,now 12.0.146~12.0.1-4build4 amd64 [installed,automatic]
nvidia-cuda-gdb/noble,now 12.0.140~12.0.1-4build4 amd64 [installed,automatic]
nvidia-cuda-toolkit-doc/noble,now 12.0.1-4build4 all [installed,automatic]
nvidia-cuda-toolkit/noble,now 12.0.140~12.0.1-4build4 amd64 [installed]
nvidia-dkms-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
nvidia-driver-550/noble,now 550.67-0ubuntu3 amd64 [installed]
nvidia-firmware-535-535.171.04/noble,now 535.171.04-0ubuntu2 amd64 [installed,auto-removable]
nvidia-firmware-550-550.67/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
nvidia-kernel-common-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
nvidia-kernel-source-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
nvidia-opencl-dev/noble,now 12.0.140~12.0.1-4build4 amd64 [installed,automatic]
nvidia-prime/noble,now 0.8.17.2 all [installed,automatic]
nvidia-profiler/noble,now 12.0.146~12.0.1-4build4 amd64 [installed,automatic]
nvidia-settings/noble,now 510.47.03-0ubuntu4 amd64 [installed,automatic]
nvidia-utils-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
nvidia-visual-profiler/noble,now 12.0.146~12.0.1-4build4 amd64 [installed,automatic]
xserver-xorg-video-nvidia-550/noble,now 550.67-0ubuntu3 amd64 [installed,automatic]
```

**Comment by LunaAmora** [comment]
The same thing happens on my computer, running these commands before installing fixes the issue for me:
```
export CC=gcc
export CXX=g++
```
Could you try this?

**Comment by vak** [comment]
helped! issue could be closed, thousand thanks!
