### ISSUE TITLE
Don't require Rust Nightly

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/HVM#352]
Bend recently updated to not need rust nightly anymore.
Since hvm also doesn't need it to work and was only saying so that users only need one version of Rust to install both crates, we can now remove this requirement.

This means removing `rust-toolchain.toml` and removing mentions of rust nightly in the README.

We could also add the minimum supported rust version to `Cargo.toml`, which I tested to be `1.74`.

**Comment by kings177** [comment]
reopening this, wouldn't it be better for the rust-toolchain.toml to have something like:

```
[toolchain]
profile = "minimal"
channel = "1.74.0"
components = ["rustfmt", "clippy"]
```

**Comment by kings177** [comment]
make sense

**Comment by steinerkelvin** [comment]
Reopening this. It's useful to have this file to enable  reproducibles builds.

**Comment by kings177** [comment]
i don't think that's necessary at all, you can just pass `pkgs.rust-bin.stable.latest.default;` to the flake.nix and that should work already, no?!

**Comment by kings177** [comment]
reclosing this.
