### ISSUE TITLE
Thread 'main' panick over 0.0 floating point number

### ISSUE THREAD

**Issue by tgoorden** [HigherOrderCO/HVM#380]
### Reproducing the behavior

HVM panics when encountering a `0.0` float. To test, try to run (parse) the following hvm code:
```
@main = 0.0
```
This will run into:
`assertion failed: expo >= -63 && expo <= 63`

To get to this error from bend, it is enough to write:
```
def main:
  return 0.0
```
This code *passes* `bend check`! Note that it is enough to write `0.0` _anywhere_ in your bend code to run into this error.

Obviously this is mightily confusing for developers.

### System Settings

Bend 0.2.33

**Comment by developedby** [comment]
This was already fixed in HVM version 2.0.14, please update.
