### ISSUE TITLE
Failed to launch kernels. Error code: invalid argument.

### ISSUE THREAD

**Issue by simofildi** [HigherOrderCO/HVM#383]
### Reproducing the behavior

Tried to execute the examples provided in README for Bend.
Every example works fine when tested using run and run-c but not with run-cu.

Example:
 Running command: bend run-cu sequential_sum.bend -s
 Returns: Failed to launch kernels. Error code: invalid argument.
 Errors: Failed to parse result from HVM.
 Expected behavior: running as run and run-c

### System Settings

 - OS: WSL, tried both on Ubuntu 20.04.6 LTS and Ubuntu 22.04.4 LTS
 - Kernel: Linux 5.15.146.1-microsoft-standard-WSL2
 - CPU: AMD Ryzen 5 3600
 - GPU: RTX 2060S
 - Cuda Version: release 12.5, V12.5.40

### Additional context

I tried to downgrade from cuda 12.5 to cuda 12.4 but nothing changed. Followed the installation guide of cuda for WSL provided by NVIDIA.

**Comment by enricozb** [comment]
This is an issue with using a GPU with insufficient L1 cache. See the [Bend FAQ](https://github.com/HigherOrderCO/Bend/blob/4d43bd940525d33cfe35caf9c7fff4f0ce1fb7f6/FAQ.md#im-getting-a-failed-to-launch-kernels-error-code-invalid-argument-error) for more information.
