### ISSUE TITLE
IOs should return an error when they fail

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/HVM#393]
**Is your feature request related to a problem? Please describe.**
Currently the IOs print on stderr when they fail and return an ERA node.
The program has no way of knowing that it failed, so the `*` will corrupt the running program and everything will be messed up.
Instead we should return some form of error.

**Describe the solution you'd like**
IOs should return a result type, like in Rust for example, with a variant for success that has the desired value and a variant for error. This way users are forced to deal with any incoming errors.

The variant for error can then return some kind of error enumeration, or error adt with the variant of the specific error and maybe some additional information, like a message from the OS.
The exact format of the error can be whatever the underlying C functions give you (like an errno or some other error code).

Ideally all IOs in the same "category" return the same error type so that it's easier to handle it in Bend.

**Describe alternatives you've considered**
Returning a tuple with the error and the value. This is shorter and simpler, but the user can ignore the error.
Somehow passing errors through the IO type, a bit like haskell. This would be way more complicated on the HVM side.
Having error be accessed externally, maybe through a separate IO call, like in C. This is obviously not good.

**Comment by enricozb** [comment]
Fixed by https://github.com/HigherOrderCO/HVM/pull/407
