### ISSUE TITLE
Implement Basic IO Functions

### ISSUE THREAD

**Issue by kings177** [HigherOrderCO/HVM#415]
- [x] Implement file reading and writing.
- [x] Add support for stdin/out operations.

**Comment by developedby** [comment]
This was already implemented in the following PRs:
https://github.com/HigherOrderCO/HVM/pull/336
https://github.com/HigherOrderCO/HVM/pull/363
https://github.com/HigherOrderCO/HVM/pull/347
https://github.com/HigherOrderCO/HVM/pull/369
https://github.com/HigherOrderCO/HVM/pull/374
https://github.com/HigherOrderCO/HVM/pull/392
https://github.com/HigherOrderCO/HVM/pull/407
