### ISSUE TITLE
Is there a need for an LSP in HVM?

### ISSUE THREAD

**Issue by nataneb32** [HigherOrderCO/HVM#88]
Probably it would need a better error handling. The ideal would be something like Rust errors messaging ( or better ).

In my view there is two approachs for a LSP. Creating something on top of the exposed api for handling error. Or creating a checker from zero. The later is not great, because this means more code to maintain.

**Comment by nataneb32** [comment]
The first approach has the need of creating an api to expose errors. Also should keep in mind how this is gonna play with languages that target hvm.

**Comment by quleuber** [comment]
I think the first one is much better from a maintainability perspective, and to help embed HVM.
Do you have some pointers to help with the first approach?

**Comment by stken2050** [comment]
I think it's good to adopt to

https://microsoft.github.io/language-server-protocol/

**Comment by nataneb32** [comment]
> I think the first one is much better from a maintainability perspective, and to help embed HVM.
> Do you have some pointers to help with the first approach?

I think that implement some of this on the parser. That will return a ParserError enum. And than some kind of typing systemish thing to catch at compile time any error, that will happend on runtime.

**Comment by nataneb32** [comment]
Rust has a good approach on the lexer and parser that says to you what was expected.
