### ISSUE TITLE
[Suggestion] Debugger

### ISSUE THREAD

**Issue by Heimdell** [HigherOrderCO/HVM#91]
It would be nice to have some form of debugger for HVM - with ability to stop at breakpoints to see what expressions are the names bound to at the moment.

**Comment by rigille** [comment]
That would definitely be nice to have ^^

**Comment by VictorTaelin** [comment]
We have the `hvm d program` command that outputs the entire reduction history with every variable ever used, but something that stopped in a specific point and showed the "stack" and bound vars would be amazing indeed.

**Comment by quleuber** [comment]
Also, it seems not much hard to add a REPL.
